source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'pg', '~> 0.17.1'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'therubyracer'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'devise'
gem 'cancancan', '~> 1.10'
gem 'carrierwave'
gem 'rails-i18n'
gem 'translit'
gem 'will_paginate'
gem 'curb'
gem 'truncate_html'
gem 'mini_magick', '~> 4.2.10'
gem 'exception_handler'
gem 'gretel'
gem 'rails-api'
gem 'vkontakte_api', '~> 1.4'
gem 'koala', '~> 2.0'
gem 'builder'
gem 'apipie-rails'
gem 'rpush'
gem 'videojs_rails'
gem 'dotenv-rails'

group :development, :test do
	gem 'spring'
	gem 'better_errors'
	gem 'binding_of_caller'
	gem 'byebug'
	gem 'faker'
	gem 'mailcatcher'
	gem 'quiet_assets'
	gem 'mina'
end
